### ISSUE TITLE
[text-to-speech] Add support for customizations

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/ios-sdk#219] opened 2016-03-28 18:16 UTC
Add support for customizations. See: https://watson-api-explorer.mybluemix.net/apis/text-to-speech-v1
There are new endpoints like /v1/pronunciation and /v1/customizations

**Comment by glennrfisher** [comment] 2016-03-28 18:17
Will do, thanks @germanattanasio!

**Comment by glennrfisher** [comment] 2016-05-07 02:14
This is a duplicate of #229.

**Closed by glennrfisher** 2016-05-07 02:14 UTC
Labels: text-to-speech
