### ISSUE TITLE
[speech-to-text]opening import file for module 'MobileCoreServices': Permission denied

### ISSUE THREAD

**Issue by somdutta123** [watson-developer-cloud/ios-sdk#509] opened 2016-11-04 10:49 UTC
I have executed each and every step from the quicktstart guide.
Expected behaviour is proper build.
I a facing two errors:
1. Command failed due to signal:Segmentation fault: 11
2.Opening import file for module 'MobileCoreServices ': Permission Denied

Xcode used: Xcode 8 beta 3
IOS SdK version : github "watson-developer-cloud/ios-sdk"

Targeted IOS version : 8.0+

**Comment by glennrfisher** [comment] 2016-11-08 20:15
Hi @somdutta123. Is there any more information you can provide that you might think would be helpful?

Since the error was with the `MobileCoreServices` framework, I assume you followed the quick start guide to try and integrate the iOS SDK into an existing application. Is that right?

If so, can you try following the quick start guide with a new project and see if you get the same error?

I seem to be able to link the `MobileCoreServices` framework in a sample application with no trouble. So I suspect it's something with your environment or application settings.

It's worth noting that I'm using Xcode 8.0. Maybe this is a bug with Xcode 8 beta 3?

**Comment by somdutta123** [comment] 2016-11-09 11:42
@glennrfisher Hi. Thanks for your response. I did everything on a fresh project. I followed the guide and integrated the SDK into a fresh project. I shall check on Xcode * beta 3 and let you know.
Can you tell me about any other noteworthy settings that I have to make?

**Comment by vherrin** [comment] 2016-11-09 14:56
Currently Xcode 8.1 is released and not beta.  The latest beta as of Nov 9 is Xcode 8.2 beta.  Can you specify the exact version and build of Xcode.  For example, the Xcode I'm running is Version 8.1 (8B62)

**Comment by glennrfisher** [comment] 2016-11-09 16:40
Here's a few interesting posts I could find through Google:

- https://github.com/Carthage/Carthage/issues/785
- http://stackoverflow.com/questions/30196440/opening-import-file-for-module-swift-permission-denied

**Comment by glennrfisher** [comment] 2016-11-09 16:43
It's possible that this issue is caused by a mismatch in Xcode / OS versions that are used. We started using the `carthage archive` command to upload binaries and save users the time of having to build the SDK on their machine. But that means the binaries that you download were created with the version of macOS and Xcode that I'm running on my machine (currently macOS 10.11.6 and Xcode 8.0 8A218a).

Can you try enforcing Carthage to build the frameworks instead of downloading the binaries? I'm curious to know what you discover:

`carthage update --platform iOS --no-use-binaries`

**Comment by somdutta123** [comment] 2016-11-10 07:19
@glennrfisher  Hi there. I had already  tried doing some of the fixes before like this one.
http://stackoverflow.com/questions/30196440/opening-import-file-for-module-swift-permission-denied
Didnt work though!
However regarding the carthage issue, I tried enforcing carthage to build the frameworks.
here is what I get.
![screen shot 2016-11-10 at 12 49 10 pm](https://cloud.githubusercontent.com/assets/23258146/20167819/1917700e-a744-11e6-8222-8f796a823bdf.png)

**Comment by somdutta123** [comment] 2016-11-10 07:20
https://github.com/Carthage/Carthage/issues/1396
Going through this. No work around as of now.

**Comment by somdutta123** [comment] 2016-11-10 07:22
@vherrin  Hello. I am currently using this.
![screen shot 2016-11-10 at 12 53 29 pm](https://cloud.githubusercontent.com/assets/23258146/20167865/5425ade6-a744-11e6-9b56-517e5b5453e1.png)

**Comment by glennrfisher** [comment] 2016-11-14 19:52
Hi @somdutta123. Can you try this again with the latest version of Xcode and the latest version of the SDK?

**Comment by glennrfisher** [comment] 2016-11-16 06:18
@sccheng made a great find: It turns out that Alamofire (one of the dependencies in earlier versions of the SDK) internally imports the `MobileCoreServices` framework. We removed the Alamofire dependency with v0.9.0 of the SDK, so it shouldn't need to be imported anymore.

I also double-checked the quick start guide by following the step-by-step directions with Xcode 8.1 and v0.9.1 of the SDK. Here's the [project][1], which builds and runs successfully on my machine.

I think everything should work okay for you using the latest version of Xcode and the latest version of the SDK, so I'm going to close this issue for now. If you still run into problems, let us know and we can reopen it.

[1]: https://ibm.box.com/s/dcmdz7lte93w7t2t1bqht6htuf7p0jba

**Closed by glennrfisher** 2016-11-16 06:18 UTC
Labels: support
