### ISSUE TITLE
Xcode 7.3: Include of non-modular header inside framework module 'WatsonDeveloperCloud.os_types'

### ISSUE THREAD

**Issue by luish** [watson-developer-cloud/ios-sdk#210] opened 2016-03-22 12:04 UTC
I am having problems to build the framework itself using Xcode 7.3 and the latest code base in the `master` branch. The carthage command seems to finish successfully and I have the `.framework` files in my `Carthage/Build/iOS` folder.

<img width="736" alt="screen shot 2016-03-22 at 11 58 12" src="https://cloud.githubusercontent.com/assets/133780/13950877/6c8e40fe-f025-11e5-8f92-729f9a11a3e0.png">

<img width="979" alt="screen shot 2016-03-22 at 11 54 42" src="https://cloud.githubusercontent.com/assets/133780/13950849/4677e9ec-f025-11e5-8d7c-cbf32db2dca5.png">

Is anyone else getting this same error?

Thanks in advance.

**Comment by glennrfisher** [comment] 2016-03-22 13:44
Thanks for letting us know about this, @luish.

I'm downloading Xcode 7.3 so we can take a look and fix this as soon as possible. Unfortunately, it looks like Apple's servers are being hammered right now, so it might take a little while...

<img width="227" alt="screen shot 2016-03-22 at 8 42 27 am" src="https://cloud.githubusercontent.com/assets/1957636/13953496/3b3627b2-f00a-11e5-86ac-d9f0bf4ce7e0.png">

**Comment by luish** [comment] 2016-03-23 11:32
Ok, @glennrfisher, please let me know if you were able to reproduce this issue.

I just found [this thread on stackoverflow](https://stackoverflow.com/questions/36171429/could-not-build-module-and-include-of-non-modular-header-inside-framework-module) and it might really be something related to Xcode 7.3.

**Comment by luish** [comment] 2016-03-23 17:22
Apparently I could managed to make it build successfully adding the file `config_types.h.in` that comes in the libogg-1.3.2 ([tar.gz link](libogg-1.3.2.tar.gz)). To be honest I don't really know if this is a solution. Please take a look at my commit https://github.com/luish/ios-sdk/commit/e94c65a56a3b832a373036d2fe3c23fc6196fd36 and hopefully it might have some light to solve this issue. If it works for you I would be glad to create a pull request with the supposed fix. :-)

<img width="804" alt="screen shot 2016-03-23 at 17 16 40" src="https://cloud.githubusercontent.com/assets/133780/13994095/248a62aa-f11b-11e5-83db-6b9b2bf051f2.png">

**Comment by glennrfisher** [comment] 2016-03-24 19:12
Unfortunately, it's going to take some time for us to track down the root cause of this problem and fix it in a way that we're comfortable with. (This [StackOverflow question](http://stackoverflow.com/questions/27776497/include-of-non-modular-header-inside-framework-module) and [Github issue](https://github.com/AFNetworking/AFNetworking/issues/2205) also seem to be promising leads.)

Our current plan is to move quickly to get our repository building with Xcode 7.3. Unfortunately, the quickest approach will be to remove the ogg and opus libraries. That will allow us to take the time to investigate the problem in more detail and make the right, lasting changes.

In the mean-time, while we're working to add support for Xcode 7.3, you can still use Xcode 7.2 to build the framework and write programs that use it. Here are instructions for installing Xcode 7.2 side-by-side with Xcode 7.3 and using it:

1. Download [Xcode 7.2](http://adcdownload.apple.com/Developer_Tools/Xcode_7.2/Xcode_7.2.dmg)
2. Open the Xcode 7.2 disk image and drag `Xcode` to your `Applications` folder.
3. When prompted that `An item named "Xcode" already exists in this location` be sure to select `Keep Both`. This will copy Xcode 7.2 to your Applications directory under the name `Xcode copy`.
4. Open your Applications directory and rename `Xcode copy` to `Xcode 7.2`.
5. Open Xcode 7.2. In the preferences panel for `Locations` set the `Command Line Tools` to `Xcode 7.2 (7C68)`.

Now Carthage is configured to use Xcode 7.2 at the command-line. And you can continue developing with the Watson Developer Cloud iOS SDK using Xcode 7.2.

<img width="749" alt="using xcode 7 2" src="https://cloud.githubusercontent.com/assets/1957636/14028357/199cb546-f1ca-11e5-8769-a0a146d26b6d.png">

**Comment by fujisaki-satoshi** [comment] 2016-03-28 11:51
I hope that this issue is resolved!

**Comment by glennrfisher** [comment] 2016-03-28 14:45
Just want to give everyone an update on our progress so far:
- The `include of non-modular header` error is caused by our use of the Ogg/Opus libraries.
- To fix the error, we are removing the Ogg/Opus libraries until we can learn how to properly import and use them with the changes made to Xcode 7.3.
- Since the Text to Speech implementation uses Opus-encoded audio, we have switched to using WAV.
- However, the [WAV header is corrupt](https://developer.ibm.com/answers/questions/180732/seems-watson-text-to-speech-service-returns-a-wav.html), so we wrote a function to manually repair the header.
- Most Text to Speech tests now pass, with the exception of the SSML test.

What remains is to investigate why the SSML test fails with WAV. A hexdump of the returned audio seems to suggest that it is OPUS-encoded instead of WAV-encoded. This may be a bug with our request or a bug with the service. Once we have solved this bug, we can re-run the tests and merge the fix to `master`.

**Comment by vherrin** [comment] 2016-03-28 14:52
Thanks for the update Glenn!

**Comment by fujisaki-satoshi** [comment] 2016-03-28 19:29
Thank you for your information!

**Comment by glennrfisher** [comment] 2016-03-28 21:37
This was fixed with PR #220.

However, to use the Watson Developer Cloud iOS SDK with Xcode 7.3, you will need to use Carthage to rebuild all dependencies (including pre-built binaries). To do so, navigate to your project directory and run the following command:

`carthage update --platform iOS --no-use-binaries`

**Comment by glennrfisher** [comment] 2016-03-28 21:38
If you have any further issues with Xcode 7.3, Swift 2.2, or anything else, please don't hesitate to post here or open a new issue. We want to make sure that all of you are good-to-go!

**Closed** 2016-03-28 21:38 UTC
Labels: bug

**Comment by luish** [comment] 2016-03-29 12:45
Many thanks for the update, @glennrfisher! :+1:
