### ISSUE TITLE
Installation via CocoaPods

### ISSUE THREAD

**Issue by tanmayb123** [watson-developer-cloud/ios-sdk#232] opened 2016-04-20 19:34 UTC
I personally prefer CocoaPods over Carthage, and some others may as well, so maybe we could use CocoaPods as well?

**Comment by glennrfisher** [comment] 2016-04-20 19:37
Hi @tanmayb123. We definitely want this SDK to be consumable with CocoaPods. It may be some time, though, before we get a chance to tackle this issue.

Just so you know, I'm going to close this issue since it is a duplicate of #127.

**Closed by glennrfisher** 2016-04-20 19:37 UTC
