### ISSUE TITLE
Add missing services to the SDK

### ISSUE THREAD

**Issue by vherrin** [watson-developer-cloud/ios-sdk#280] opened 2016-05-23 14:45 UTC
**Language Services**

- [x] Alchemy Language
- [x] Conversation 
- [x] Dialog 
- [x] Document Conversion
- [x] Language Translation 
- [x] Natural Language Classifier 
- [x] Personality Insights 
- [x] Relationship Extraction
- [ ] Retrieve and Rank (#328)
- [x] Tone Analyzer 

**Speech Services**

- [x] Speech to Text 
- [x] Text to Speech

**Vision Services** 

- [x] Alchemy Vision
- [x] Visual Recognition

**Data Insights Services** 

- [x] Alchemy Data News
- [x] Tradeoff Analytics

**Comment by glennrfisher** [comment] 2016-05-24 19:51
I removed Visual Insights and Concept Expansion from this list since they have been deprecated.

(I really dislike editing other people's comments--it seems weird that GitHub even allows us to do that. But in this case I thought it made sense, since we are using the checklist in your comment to track this issue's state.)

**Comment by glennrfisher** [comment] 2016-06-22 02:45
Only 2 services left! Just Retrieve and Rank and Concept Insights. :)

**Comment by germanattanasio** [comment] 2016-06-22 04:42
I'm going to remove Concept Insights at this point you kind of imagine why.

**Comment by glennrfisher** [comment] 2016-06-23 10:14
And then there was one. Cool!

I'm going to close this issue since at this point it is a duplicate of #328. ;)

**Closed by glennrfisher** 2016-06-23 10:14 UTC
Labels: general-sdk
