### ISSUE TITLE
Mixing AVAudioSessions

### ISSUE THREAD

**Issue by JamieGilbertIBM** [watson-developer-cloud/ios-sdk#453] opened 2016-09-20 14:47 UTC
Opening on behalf of customer:

The new framework for iOS Speech to Text which comes on iOS-SDK requires the use of 'recognizeMicrophone()'. Previously, this SDK required creating an AVAudioSession. It is easier now, but now any previous AVAudioSessions are cut off as soon as microphone starts. When I'm playing back a sound (voice), as soon as I call recognizeMicrophone from your SDK all audio playback halts. 

I've spent a lot of time getting the microphone to start record while the previous playback is finishing. Do you know of a way to avoid cutting off existing sessions? Otherwise, this new module update is useless to me, I'll have to revert back so that I can control the session. My app is very streamlined to where the user speaks, then the computer speaks, then the user is able to speak immediately once the playback is finished.

**Comment by kteman** [comment] 2016-09-20 15:07
I am using AVAudioPlayer to playback audio, which gets cuts off as soon as I call recognizeMicrophone(). I have already set the audio session shared instance to play and record.

**Comment by glennrfisher** [comment] 2016-09-21 21:45
The culprit here is probably [this line](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/SpeechToTextV1/SpeechToTextRecorder.swift#L122) in the SDK that sets the shared `AVAudioSession` to `PlayAndRecord`.

For reference, here is documentation on the [`AVAudioSessionCategoryPlayAndRecord`](https://developer.apple.com/reference/avfoundation/avaudiosessioncategoryplayandrecord) type.

Are you creating a custom session, @kteman? The iOS SDK uses the shared `AVAudioSession` to access the microphone. The documentation includes this interesting information about mixing audio sessions:

> By default, using this category implies that your app’s audio is nonmixable—activating your session will interrupt any other audio sessions which are also nonmixable. To allow mixing for this category, use the mixWithOthers option.

Can you try making the `AVAudioSession` that you use in your application mixable?

If that doesn't fix the problem then we will have to give some thought to changes in the SDK around the `AVAudioSession` that's used to record.

(We have to figure out the balancing act between making it customizable so that users like yourself can have more control over the `AVAudioSession` while still making it easy-to-use for users who don't want to manage an `AVAudioSession`.)

**Comment by kteman** [comment] 2016-09-21 23:46
Glenn,

First wanted to take a moment to say I am excited to see I am speaking with another competent developer. I can tell already you have a great head on your shoulders. And you look like a young guy and very smart for a young guy. In this case, I think your head is in exactly the right place, and right along my lines of thinking as well.

Next, I agree, I love simplifying the use of an SDK and the changes you did to arrive at 'recognizeMicrophone()' are beautiful and elegant, and hooking it up was simply a breeze. Your SDK in my opinion represents a clean interface of exactly what it should be.

To answer your questions.

> Are you creating a custom session, @kteman?
I was when using the previous version of the SDK (shown at bottom). But, with my AVAudioPlayers I am simply creating them and playing them, such as this:
`let player:AIMMAudioPlayer = try AIMMAudioPlayer(data: data)`
and this
`player.play()`
(AIMMAudioPlayer is a superclass of AVAudioPlayer which does nothing special, but only contains a few properties)

I think our thinking is close. Regarding my previous method of using the SDK with a custom session (at bottom), my hope is that switching from shared session as you currently are using to a custom session is not what is required.

> Can you try making the AVAudioSession that you use in your application mixable?
Just tried, it still had the exact same effect (any AVAudioPlayers created and that were playing are cut off when calling 'recognizeMicrophone()').

I did that by changing my initialization to this (which occurs before anything else, including before any AVAudioPlayers are created):
`override init() {
                try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, withOptions: [**AVAudioSessionCategoryOptions.MixWithOthers**, AVAudioSessionCategoryOptions.DefaultToSpeaker])`


Using the previous version of your framework, when things were working correctly meaning the starting of the microphone session would not cut off the AVAudioPlayer, I using the following approach (which took some fine tuning to arrive at)...

First I set the shared session configuration (before anything else happens):
`override init() {
                try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord, withOptions: [AVAudioSessionCategoryOptions.DuckOthers, AVAudioSessionCategoryOptions.DefaultToSpeaker])`

Then, I lazy load a new AVCaptureSession (not a shared session), which is instantiated just before the microphone is added to the session, in which I set 'usesApplicationAudioSession' to false. The setting of this variable to false was the key in getting these sessions not to collide (the playing audio to not be cut off by starting the microphone session).
`        //Translating speech - IBM Watson
        lazy var captureSession:AVCaptureSession = {
                let captureSession = AVCaptureSession()
                captureSession.usesApplicationAudioSession = false
                
                let microphoneDevice = AVCaptureDevice.defaultDeviceWithMediaType(AVMediaTypeAudio)
                let microphoneInput = try? AVCaptureDeviceInput(device: microphoneDevice)
                
                if captureSession.canAddInput(microphoneInput) {
                        captureSession.addInput(microphoneInput)
                }
                
                return captureSession
        }()
`

Then, just after when initializing IBM Watson I add the output to the session:

`                guard let output = outputOpt else {
                        return
                }
                
                transcriptionOutput = output.0
                self.endSpeechRecognitionStream = output.1
                
                if captureSession.canAddOutput(transcriptionOutput) {
                        captureSession.addOutput(transcriptionOutput)

                captureSession.startRunning()

`

Lastly, Glenn, I've become a little more familiar with AVFoundation and how it applies in these scenarios, especially working with the microphone. Please shoot questions my way. My guess is (but I could be wrong) that there is nothing I can do from outside of your module to prevent your module from cutting off AVAudioPlayer audio at this time.

As an additional step to test before you wrote back: I removed every piece of code in my app that was referencing the AV audio shared session, thinking that you guys were probably using the shared session as well. (My app is complex and has many areas which use the shared session) Removing all of these references had no effect, in that starting 'recognizeMicrophone()' still cut off any currently playing AVAudioPlayers (which do not manually have to be added to a session, but I suspect are added to the shared session since this conflict exists).

Thanks, and feel free to shoot questions my way as I may be able to help you achieve that perfect balance between simplicity and robustness.

Kevin

**Comment by kteman** [comment] 2016-09-21 23:52
My app is a dating app which consists of dialog and questions between the user and the app, much like a conversation between two people. Think Siri meets dating app.

**Comment by kteman** [comment] 2016-10-11 23:24
Hi, I was wondering how your progress is coming for this issue? With the service currently cutting off my existing audio, I would have to pull it from my project if this can't be resolved...
Thanks.

**Comment by glennrfisher** [comment] 2016-10-18 16:30
Hi @kteman. Thank you for the very kind words in your earlier message.

Unfortunately, our team is on-the-hook to deliver enhancements to the SDK for some upcoming IBM conferences--that means that we won't be able to take the time to investigate this issue until at least the third week of November.

Since the SDK is open-source, though, we encourage you to fork it and make changes. Especially since you sound very knowledgeable about `AVAudioSession`, we would gladly welcome your improvements and suggestions.

**Comment by kteman** [comment] 2016-10-20 22:54
Hi Glenn,

Is there a way for me to go forward wrapping the Objective-C version of this module so that I can update my project to Swift 3, and proceed with the ability to control the session?

Do you guys still have an Objective-C wrapper? And is this a feasible solution or would it be dangerous for me to proceed "off the grid" with an unsupported wrapper.

My issue is that you guys are taking a more general approach to this SDK which removes the ability to control the session as I need.

Please discuss with team and let me know if this is a feasible solution. Or how I might be able to proceed. I especially need the session issues resolved, but beyond that I would really like to get my project over to Swift 3 as well.

**Comment by glennrfisher** [comment] 2016-10-24 03:36
You can use the Objective-C SDK, but it is deprecated and will not be supported.

We are currently working on modifying the SDK for Swift 3. It should be ready soon.

**Comment by kteman** [comment] 2016-11-02 23:06
Hi, and will this include the ability to manage the session? This is crucial to my needs as well as anyone who is playing back audio while also wanting to start a speech recognition session.

**Comment by glennrfisher** [comment] 2016-11-07 18:02
Hi @kteman. The Swift 3.0 version won't have a fix for this issue, unfortunately. We have it on our task list for this sprint, though, and hope to take a look this week or next. Sorry for the delay!

**Comment by kteman** [comment] 2016-11-09 23:53
Glenn, more than excited that you guys will start working on it this sprint. That works for me. It's been a hiccup in my project for sometime.

Thanks again, Kevin

**Comment by sccheng** [comment] 2016-11-18 21:01
Hi @kteman,

I've started looking into your issue yesterday. To try and recreate it, I created an empty app with the following method that gets called from `viewDidLoad`:

```
func setupAudio() {
        try! AVAudioSession.sharedInstance().setActive(true)
        try! AVAudioSession.sharedInstance().setCategory(AVAudioSessionCategoryPlayAndRecord,
                                                         with: [.mixWithOthers, .defaultToSpeaker])
        
        let stockFileURLPath = Bundle.main.path(forResource: "test", ofType: "wav")
        let stockFileURL = NSURL.fileURL(withPath: stockFileURLPath!)
        audioPlayer = try! AVAudioPlayer(contentsOf: stockFileURL)
        audioPlayer.prepareToPlay()
}
```

Then, I added 2 buttons, `play` and `record`, which are hooked up to separate IBAction methods. For the `play` button, I call `audioPlayer.play()`; for the `record` button, I call our SpeechToText `recognizeMicrophone()` method.

I then tested the app by clicking `play`, and while the audio was still playing from the file, I clicked `record`. When I tested this, the audio didn't cut off as you had observed. The audio continued to play from the file, and I'm able to record and get back a response from Watson at the same time.

Could you help me out? I'm wondering if I've done something differently, in trying to recreate your situation. Is there a simple example app that you could help me build, so I can try to test out and fix your issue?

**Comment by kteman** [comment] 2016-11-20 00:34
Stephanie,

Thanks for looking into it. I've gone ahead and converted my project to Swift 3 (wow, what an undertaking that was! 9 hours or so), then dropped in your latest Swift 3 SDK, then tested it.

It is definitely still a problem in my project.

I've taken out all variables which I feel might impact this, and I'm getting the same result.

I was thinking, perhaps you could send me your sample project, and I could reproduce my setup on there. One thing I see that's different from my setup is you're initing with a file URL, and I am initing from data...

`let player:AIMMAudioPlayer = try AIMMAudioPlayer(data: data)`

AIMMAudioPlayer is a simple subclass of AVAudioPlayer which does nothing but contain a couple variables.

I have set the audio session categories, and active, exactly as you have, and eliminated all other code that could possibly be involved in the audio session. And yet still, as soon as I call...

`watsonSpeechToText.recognizeMicrophone(settings: settings, model: nil, customizationID: nil, learningOptOut: true, compress: true, failure: self.watsonFailure!, success: self.watsonSuccess!)`

The audio cuts off. If I comment 'recognizeMicrophone' out, the audio continues to play with no problems...

If you can think of anything let me know, but was thinking if you can send me your sample project, I can tweak some things and get it to break. Or, conversely, I might figure out I'm doing something wrong... although I can't think of what it is!

Thanks,
Kevin

**Comment by kteman** [comment] 2016-11-20 00:50
[Audio Cut Off.mp4.zip](https://github.com/watson-developer-cloud/ios-sdk/files/601813/Audio.Cut.Off.mp4.zip)

Video above

**Comment by sccheng** [comment] 2016-11-21 20:00
Kevin,

Just to make sure we cover all our bases, I tried a few changes based on a few differences you pointed out/I saw:

I tried creating the AVAudioPlayer from data: 
`audioPlayer = try! AVAudioPlayer(data: Data(contentsOf: stockFileURL))`
But it didn't make a difference.

I also tried passing the same parameters to recognizeMicrophone() as you're doing, but didn't see anything different.

I've attached the sample project I created - let me know if you see anything that could be an issue!

[AVAudioSession Test.zip](https://github.com/watson-developer-cloud/ios-sdk/files/604642/AVAudioSession.Test.zip)

**Comment by kteman** [comment] 2016-11-23 00:39
Stephanie,

Good thinking on those checks. I spent some time tonight getting your sample app started. To do that, I destroyed the Carthage links to Restkit and specified scripts and SpeechKitV1 frameworks and re-dragged in the folders with files directly, then added my credentials (removed them before sending back to you). You'll see in the project I sent back, modified.

Then I ran on iPhone 7 to see the results. And although the audio was not cut completely off, the volume drastically reduces, then fades back slowly.. please see the video I attached.

I have observed this behavior especially with iPhone 7, plenty, in my own practices. I was able to get around this previously with your module by controlling the av audio session (as mentioned at beginning of this post with Glenn). However, even on iPhone 6 audio was completely cut off for me once you guys switched from requiring us to create the audio session some versions back to recognizeMicrophone() where you handle it automatically.

Any idea why the volume is so drastically reducing there?

Kevin

[AVAudioSession Test.zip](https://github.com/watson-developer-cloud/ios-sdk/files/607890/AVAudioSession.Test.zip)

[test.mp4.zip](https://github.com/watson-developer-cloud/ios-sdk/files/607892/test.mp4.zip)

**Comment by kteman** [comment] 2016-11-23 00:42
Specifically I need to be able to handle the session so that I can avoid reduction in volume there, or as is the case with my app it is completely cutting off the audio...

I have not figured out the difference between your sample app and mine, as to why mine completely cuts off audio. The sample app I've sent back to you is exactly how I ran it...

Thanks, Kevin

**Comment by kteman** [comment] 2016-11-23 00:43
And I appreciate your help

**Comment by kteman** [comment] 2016-11-23 00:44
Also added a key in the plist required to start this project and use microphone on device...

2016-11-22 17:00:15.399949 AVAudioSessionTest[949:283945] [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by sccheng** [comment] 2016-11-29 15:49
Hey Kevin,

Just wanted to update you - I was out most of last week for Thanksgiving (happy late Thanksgiving!), but am back in the office now.

I started testing on a physical phone (a 6s), and I notice that the audio does cut off for a split second, but continues afterwards, skipping a bit of the audio. I'm poking around a bit in the SDK now, to see what might be the problem.

Thanks for updating the sample app, I appreciate it! I'll let you know if I make progress.

**Comment by sccheng** [comment] 2016-11-29 22:42
@kteman,

Hey! So I ended up doing some testing and removing the lines in the SDK where we set the category and the session to active (specifically, [lines 129 and 130](https://github.com/watson-developer-cloud/ios-sdk/blob/master/Source/SpeechToTextV1/SpeechToTextRecorder.swift#L129)).

On my end, I notice that this stops the slight pause/cut-off when I press "record" while the audio is playing.

Can you test this for me and let me know if it fixes things, or if anything different happens?

Thanks!!

[AVAudioSession Test.zip](https://github.com/watson-developer-cloud/ios-sdk/files/620407/AVAudioSession.Test.zip)

**Comment by kteman** [comment] 2016-12-01 00:01
AWE-SOME!!!

Worked perfectly in my tests. With that change.. I should be able to isolate what else may be an issue in my project causing it to completely cut off.. then I can use the sample project as a reference to isolate the remaining issues, since your sample app works perfectly.

I've actually heard of this before, well experienced it myself, setting sessions to active does seem to affect previously playing audio in many cases - for example with OpenEars, the offline voice interpretation module.

I'm very happy Stephanie, you've made my day. I'll be able to address that one as soon as I get an opportunity.

From my standpoint, although I have not investigated at all, seems like you might be able to take out those lines. I would advise against having them due to the issues I've seen on iPhone 7 and it's speaker which works differently than iPhone 6. If you have an iPhone 7 handy, try switching from internal speaker to external while you're listening to a voicemail, you'll see the audio takes a long time to fade into the external speaker. Not sure if I have a defective phone or not, but I've already filed a bug with Apple.

I really appreciate your help. I'll be sending an email through the sales chain through Elias letting him know you've came through to help me out on this.

I don't think I'll need anything else from your end, I would like to hear an update though on whether you decide to remove those lines or not.

Kevin (happy face)

**Comment by sccheng** [comment] 2016-12-01 22:13
Hey Kevin,

Really glad that this worked out for you! The team will most likely have a discussion late this week/early next week about what we want to do with those two lines. We can post an update in here when we make a decision.

Thanks for helping to test things along the way!

**Comment by sccheng** [comment] 2016-12-06 20:47
Hey Kevin,

We decided in the end to move those lines from SpeechToTextRecord.swift to SpeechToText.swift. That way, if users want an easy way to use the `recordMicrophone` function without needing to update the AVAudioSession, they can use that function within `SpeechToText.` However, if users want more control over the AVAudioSession, among other things, they can use the `startMicrophone` function found in `SpeechToTextSession.`

The exact changes made can be found in #549.

**Closed by sccheng** 2016-12-06 20:47 UTC
Labels: bug, speech-to-text, support
